# Pricing of Maturity Monitored Barrier Security

This notebook prices the _"NBC Auto Callable Contingent Memory Income Note"_ described in this [link](https://nbcstructuredsolutions.ca/detailProduit.aspx?lequel=5317#documents).  This note is referred to as the _"security"_ for the remainder of this Notebook. 

This will be accomplished by first creating a function to generate the payout of the security if given the return of the underlying asset, which is the _Shares® Core S&P 500 Index ETF (CAD-Hedged)_.   This asset is referred to the _"ETF"_ for the remainder of the Notebook.

With this function defined we estimate the volatility of the ETF and then perform a Monte Carlo simulation of the ETF performance and the resulting security payout.  With the population of payout profiles we can estimate the fair price of the security.

## 1. Create the security payout function

#### Import some necessary modules.

In [167]:
import matplotlib.pyplot as plt
import numpy as np
import os
import pandas as pd
import seaborn as sns

%matplotlib inline

#### Define some variables

In [168]:
risk_free = 0.03     # Risk-free interest rate
barrier = -0.25      # Maturity-monitored barrier
coupon = 5.75 / 2    # Semi-annual coupon payment
call_threshold = 0.1 # Call threshold
face_value = 100     # Face value of the security
pf = 0.0             # Participation Factor
deferred_ppf = 0.05  # Deferred payment participation factor
current_ppf = 0.01   # Current payment participation factor
vrt = 0.0            # Variable return threshold

paydays = pd.to_datetime(['2020-08-18', '2021-02-18',
                          '2021-08-18', '2022-02-17',
                          '2022-08-18', '2023-02-17',
                          '2023-08-18', '2024-02-16',
                          '2024-08-19', '2025-02-18',
                          '2025-08-18', '2026-02-18',
                          '2026-08-18', '2027-02-18', '2027-02-25'], 
                           infer_datetime_format=True)

#### Calculate the discount factors for February 25 and March 3, 2020

In [179]:
t_feb = (paydays - pd.to_datetime('2020-02-25', infer_datetime_format=True)).days.values / 365.2425
t_mar = (paydays - pd.to_datetime('2020-03-3', infer_datetime_format=True)).days.values / 365.2425
z_feb = np.power(1 + 0.5*risk_free, -2*t_feb)
z_mar = np.power(1 + 0.5*risk_free, -2*t_mar)

array([0.98583402, 0.97115588, 0.95693029, 0.94275936, 0.928874  ,
       0.91511854, 0.90164028, 0.88836054, 0.87506234, 0.86210377,
       0.84947559, 0.83682769, 0.82456976, 0.81229269, 0.81182926])

#### Test the payout function with the examples given in this [link](https://nbcstructuredsolutions.ca/_afficheDocument.aspx?doc=05317_EN_CLIENT_SUMMARY.pdf&secur=0&rnd=0.01401764).

In [169]:
sample_returns = np.array([[ -9, -41, -12, -42,   -46, -48, -46.5, -50,   -47, -45.5, -47,   -43, -49,   -50],
                           [ -5,  -3,   6, -10,   -41, -46, -41,    -9,   -20, -49,   -45.5, -44, -41.5, -15],
                           [ -5, -10,  -7, -13.5, -46, -50, -47,   -46.5, -47, -42,   -44,   -14,  -4,    35],
                           [-10, -14,  -4, -13,   -11,  25,   1,    50,   -40, -60,    -5,     5,  95,     5]]).T/100.0

expected_payout = np.zeros((sample_returns.shape[0] + 1, sample_returns.shape[1]))
expected_payout[0, 0] = 2.875
expected_payout[2, 0] = 6.40
expected_payout[-1, 0] = 50

expected_payout[[0, 1, 3, 8], 1] = 2.875
expected_payout[2, 1] = 2.935
expected_payout[7, 1] = 12.3
expected_payout[-2, 1] = 14.875
expected_payout[-1, 1] = 100

expected_payout[[0, 1, 2, 3, -3], 2] = 2.875
expected_payout[-4, 2] = 23.55
expected_payout[-2, 2] = 3.225 + 100

expected_payout[0:5, 3] = 2.875
expected_payout[5, 3] = 3.125 + 100

print('Sample Returns:')
print(sample_returns)
print('\nExpected Payout:')
print(expected_payout)


Sample Returns:
[[-0.09  -0.05  -0.05  -0.1  ]
 [-0.41  -0.03  -0.1   -0.14 ]
 [-0.12   0.06  -0.07  -0.04 ]
 [-0.42  -0.1   -0.135 -0.13 ]
 [-0.46  -0.41  -0.46  -0.11 ]
 [-0.48  -0.46  -0.5    0.25 ]
 [-0.465 -0.41  -0.47   0.01 ]
 [-0.5   -0.09  -0.465  0.5  ]
 [-0.47  -0.2   -0.47  -0.4  ]
 [-0.455 -0.49  -0.42  -0.6  ]
 [-0.47  -0.455 -0.44  -0.05 ]
 [-0.43  -0.44  -0.14   0.05 ]
 [-0.49  -0.415 -0.04   0.95 ]
 [-0.5   -0.15   0.35   0.05 ]]

Expected Payout:
[[  2.875   2.875   2.875   2.875]
 [  0.      2.875   2.875   2.875]
 [  6.4     2.935   2.875   2.875]
 [  0.      2.875   2.875   2.875]
 [  0.      0.      0.      2.875]
 [  0.      0.      0.    103.125]
 [  0.      0.      0.      0.   ]
 [  0.     12.3     0.      0.   ]
 [  0.      2.875   0.      0.   ]
 [  0.      0.      0.      0.   ]
 [  0.      0.      0.      0.   ]
 [  0.      0.     23.55    0.   ]
 [  0.      0.      2.875   0.   ]
 [  0.     14.875 103.225   0.   ]
 [ 50.    100.      0.      0.   ]]


#### Define the payout function

In [171]:
def payout(returns, evaluation_date):
    """
    Args:
        returns (np.array):  [n_dates, n_simulations] The ETF returns.
        evaluation_date (pd.TimeStamp):  Date to price the security.
        
    Returns:
        np.array:  [n_dates, n_simulations]  The resulting payouts.
        pd.TimeStamp:  Redemption Date
        float: Redmeption amount
    """
    n_dates = returns.shape[0]
    n_sims = returns.shape[1]

    # Determine the returns that are above the barrier (hits)
    hits = returns >= b
    miss = np.logical_not(hits)
    
    # Calculate the memory
    memory = np.zeros_like(returns)
    for i in range(1, n_dates):
        memory[i, :] = (memory[i - 1, :] + 1) * miss[i - 1, :]
    
    # Calculate deferred payment variable return if memory > 0
    deferred = (face_value * (returns - barrier) * deferred_ppf) * (memory > 0)
    
    # Calculate the Current Payment Variable Return
    variable = face_value * np.clip(returns - vrt, a_min=0.0, a_max=None) * current_ppf

    # Calculate the total coupon payment
    coupons = hits * (coupon * (memory + 1) + deferred) + variable
    del deferred, variable
    
    # Move all coupons upto call limit has been achieved to the payout array
    # Dummy created so argmax returns the size of the array if limit not volated
    payout = np.zeros((n_dates + 1, n_sims))
    dummy = np.vstack((returns, np.ones((1, n_sims)) * (call_threshold + 1)))
    hit_limit = np.argmax(dummy > call_threshold, axis=0) + 1
    del dummy
    for i in range(n_sims):
        h = min(hit_limit[i], n_dates)
        payout[:h, i] = coupons[:h, i]
    del coupons
    
    # Add the maturity Redemption Payment
    limit1 = min(call_threshold, 0.0)
    hit_limit -= 1
    for i in range(n_sims):
        if hit_limit[i] < n_dates:
            maturity_date_index = hit_limit[i]
            r = returns[hit_limit[i], i] 
        else:
            maturity_date_index = n_dates
            r = returns[-1, i] 

        if r > limit1:
            payout[maturity_date_index, i] = payout[maturity_date_index, i] + face_value * (1 + vrt)
        elif r >= barrier:
            payout[maturity_date_index, i] = payout[maturity_date_index, i] + face_value
        else:
            payout[maturity_date_index, i] = payout[maturity_date_index, i] + face_value * (1 + r)
    
    # Calculate present value of each simulation
    t = (paydays - evaluation_date).days / 365.2425
    
    
    
    return payout

# Run test
c = payout(sample_returns, issue_date)
if np.max(np.abs(c - expected_payout)) > 0:
    print("Coupon error detected in test set.")
    print(c - expected_payout)
else:
    print("Exact match with test set!!")


Exact match with test set!!
